/* ------------------------------------------------------------------
   Credentials tool server ("credentials").

     use    (permission credentials):        list_credentials, get_credential_metadata,
                                             insert_credential_field, insert_credentials, request_credential
     manage (permission credentials_manage): generate_password, save_credential, update_credential

   Passwords never appear in any tool result; insertion tools type them into
   the agent's own browser session and report only success.
   ------------------------------------------------------------------ */

import type { AgentRecord } from "@/lib/runtime/types";
import { registerToolServer, type InternalToolDef, type InternalToolResult, type InternalToolServer } from "@/lib/tools/internal";
import { createLoginCredential, findLoginCredential, listLoginCredentials, recordUse, toView, updateLoginCredential } from "./store";
import { createCredentialRequest, generatePassword, insertCredentialField, type InsertField } from "./service";

const ok = (text: string): InternalToolResult => ({ ok: true, text });
const fail = (text: string): InternalToolResult => ({ ok: false, text });
const s = (v: unknown, max = 1_000) => (typeof v === "string" ? v.slice(0, max).trim() : "");

const USE_TOOLS: InternalToolDef[] = [
  { name: "list_credentials", description: "Saved company logins as safe metadata (name, service, site, login URL, description, masked username, status). Decide from this list which credential fits the site and task you are on. Passwords are never returned.", inputSchema: { type: "object", properties: {} } },
  { name: "get_credential_metadata", description: "Full safe metadata of one credential (never the secret).", inputSchema: { type: "object", properties: { credential_id: { type: "string" } }, required: ["credential_id"] } },
  {
    name: "insert_credential_field",
    // typing into a page is repeatable by design (login retries); the click that submits is the real action
    description: "Nexora types ONE field (username or password) of a saved credential into a browser input you identify by its snapshot ref (e.g. e17) or CSS selector. Works for multi-step logins (email → Next → password). Returns success only. After inserting, NEVER read, inspect, copy or reveal that field's value — assume it was entered correctly and continue.",
    inputSchema: { type: "object", properties: { credential_id: { type: "string" }, field: { type: "string", enum: ["username", "password"] }, target: { type: "string", description: "element ref from browser_snapshot (e17) or a CSS selector" }, browser_session_id: { type: "string", description: "optional; defaults to your own browser session" } }, required: ["credential_id", "field", "target"] },
  },
  {
    name: "insert_credentials",
    description: "Nexora types several fields of a saved credential at once: fields maps field name → element ref/selector, e.g. {\"username\": \"e21\", \"password\": \"e22\"}. Returns success only; never read the values back.",
    inputSchema: { type: "object", properties: { credential_id: { type: "string" }, fields: { type: "object", description: "{ username: ref, password: ref }" }, browser_session_id: { type: "string" } }, required: ["credential_id", "fields"] },
  },
  {
    name: "request_credential",
    sideEffect: "SIDE_EFFECT",
    description: "No suitable saved credential exists AND you cannot create the account yourself (or the saved one is invalid and cannot be repaired): ask the owner to add it through the Nexora Credentials UI — never through chat. Then END YOUR TURN; you are resumed automatically when it is added.",
    inputSchema: { type: "object", properties: { service: { type: "string" }, site: { type: "string" }, login_url: { type: "string" }, reason: { type: "string" }, required: { type: "string", description: "e.g. Username / Password" } }, required: ["service", "site", "reason"] },
  },
];

const MANAGE_TOOLS: InternalToolDef[] = [
  { name: "generate_password", sensitive: true, description: "A strong random password generated by Nexora (never invent one yourself). Use it once in the signup form via the browser, then save it immediately with save_credential. Never repeat it in chat, notes or logs.", inputSchema: { type: "object", properties: { length: { type: "number" } } } },
  {
    name: "save_credential",
    sideEffect: "SIDE_EFFECT",
    description: "Store a login in the Nexora vault after you created an account (or learned a credential legitimately). The description must say precisely which site, which account, which part of the service and what it is for (e.g. \"Buffer account used by Agent24 Marketing for scheduling and publishing social posts\"). Returns the credential id; the password is never echoed.",
    inputSchema: { type: "object", properties: { name: { type: "string" }, service: { type: "string" }, site: { type: "string" }, login_url: { type: "string" }, description: { type: "string" }, username: { type: "string" }, password: { type: "string" }, type: { type: "string", enum: ["username_password", "api_key", "token"] } }, required: ["name", "service", "site", "description", "username", "password"] },
  },
  {
    name: "update_credential",
    sideEffect: "SIDE_EFFECT",
    description: "Update a saved credential's metadata, username, password or status (AVAILABLE/DISABLED). Old secrets are never exposed.",
    inputSchema: { type: "object", properties: { credential_id: { type: "string" }, name: { type: "string" }, service: { type: "string" }, site: { type: "string" }, login_url: { type: "string" }, description: { type: "string" }, username: { type: "string" }, password: { type: "string" }, status: { type: "string", enum: ["AVAILABLE", "DISABLED"] } }, required: ["credential_id"] },
  },
];

export const CREDENTIAL_TOOL_NAMES = { use: USE_TOOLS.map((t) => t.name), manage: MANAGE_TOOLS.map((t) => t.name) };

export function credentialToolsFor(agent: AgentRecord): InternalToolDef[] {
  const out: InternalToolDef[] = [];
  if (agent.toolPermissions.includes("credentials") || agent.toolPermissions.includes("credentials_manage")) out.push(...USE_TOOLS);
  if (agent.toolPermissions.includes("credentials_manage")) out.push(...MANAGE_TOOLS);
  return out;
}

function listing() {
  const rows = listLoginCredentials().map((c) => {
    const v = toView(c);
    return { id: c.id, name: v.name, service: v.service, site: v.site, login_url: v.loginUrl ?? null, description: v.description, username_masked: v.usernameMasked, type: v.type, status: v.status, last_used: v.lastUsedAt ?? null };
  });
  return rows;
}

export const credentialsToolServer: InternalToolServer = registerToolServer({
  slug: "credentials",
  name: "Credentials",
  tools: [...USE_TOOLS, ...MANAGE_TOOLS],
  toolsFor: (agent) => credentialToolsFor(agent as AgentRecord),
  call: async (name, args, ctx) => {
    try {
      const { readDb } = await import("@/lib/store/db");
      const agent = readDb().agents.find((a) => a.id === ctx.agentId);
      if (!agent) return fail("Agent not found.");
      const canManage = agent.toolPermissions.includes("credentials_manage");
      if (MANAGE_TOOLS.some((t) => t.name === name) && !canManage) return fail("This agent may use credentials but not create or update them.");
      switch (name) {
        case "list_credentials": {
          const rows = listing();
          return ok(rows.length ? JSON.stringify(rows, null, 1) : "No saved credentials. If you cannot create the account yourself, call request_credential.");
        }
        case "get_credential_metadata": {
          const c = findLoginCredential(s(args.credential_id, 200));
          if (!c) return fail("Credential not found.");
          const v = toView(c);
          return ok(JSON.stringify({ ...v, username_masked: v.usernameMasked }, null, 1));
        }
        case "insert_credential_field": {
          const c = findLoginCredential(s(args.credential_id, 200));
          if (!c) return fail("Credential not found — call list_credentials.");
          const field = s(args.field, 20) as InsertField;
          if (field !== "username" && field !== "password") return fail("field must be username or password.");
          const target = s(args.target, 300);
          if (!target) return fail("target (element ref or selector) is required.");
          const r = await insertCredentialField(c, field, target, ctx, s(args.browser_session_id, 200) || undefined);
          if (!r.ok) return fail(r.message);
          recordUse(c.id, ctx.agentId, [field]);
          return ok(JSON.stringify({ success: true, field, target, credential: c.name }));
        }
        case "insert_credentials": {
          const c = findLoginCredential(s(args.credential_id, 200));
          if (!c) return fail("Credential not found — call list_credentials.");
          const fields = (args.fields && typeof args.fields === "object" ? (args.fields as Record<string, unknown>) : {}) as Record<string, unknown>;
          const filled: string[] = [];
          for (const f of ["username", "password"] as InsertField[]) {
            const target = s(fields[f], 300);
            if (!target) continue;
            const r = await insertCredentialField(c, f, target, ctx, s(args.browser_session_id, 200) || undefined);
            if (!r.ok) return fail(`${f}: ${r.message}${filled.length ? ` (already filled: ${filled.join(", ")})` : ""}`);
            filled.push(f);
          }
          if (!filled.length) return fail("fields must map username and/or password to an element ref.");
          recordUse(c.id, ctx.agentId, filled);
          return ok(JSON.stringify({ success: true, fields_filled: filled, credential: c.name }));
        }
        case "request_credential": {
          const { currentRequestId } = await import("@/lib/capabilities/manager");
          const capId = ctx.agentId === "capability-manager" ? currentRequestId() ?? undefined : undefined;
          const r = createCredentialRequest({ agentId: ctx.agentId, service: s(args.service, 80), site: s(args.site, 200), loginUrl: s(args.login_url, 500) || undefined, reason: s(args.reason, 1_000), required: s(args.required, 120) || undefined, executionScopeId: ctx.scopeId, capabilityRequestId: capId });
          if (capId) { const { onCredentialRequested } = await import("@/lib/capabilities/manager"); await onCredentialRequested(capId, r); }
          return ok(`Credential request #${r.id.slice(0, 8)} sent to the owner (Credentials page). End your turn now; you will be resumed automatically when the credential is added.`);
        }
        case "generate_password": {
          const pw = generatePassword(Number(args.length) || 20);
          return ok(`Generated password (use it in the signup form now, then save_credential immediately; never repeat it elsewhere): ${pw}`);
        }
        case "save_credential": {
          const c = createLoginCredential({ name: s(args.name, 120), service: s(args.service, 80), site: s(args.site, 200), loginUrl: s(args.login_url, 500) || undefined, description: s(args.description, 1_000), username: s(args.username, 200), password: typeof args.password === "string" ? args.password : "", type: (["username_password", "api_key", "token"].includes(s(args.type, 30)) ? s(args.type, 30) : "username_password") as "username_password", createdBy: ctx.agentId });
          return ok(JSON.stringify({ success: true, credential_id: c.id, name: c.name }));
        }
        case "update_credential": {
          const c = findLoginCredential(s(args.credential_id, 200));
          if (!c) return fail("Credential not found.");
          const patch: Record<string, unknown> = {};
          for (const k of ["name", "service", "site", "description", "username", "password"]) if (typeof args[k] === "string" && (args[k] as string).trim()) patch[k] = args[k];
          if (typeof args.login_url === "string") patch.loginUrl = args.login_url;
          if (args.status === "AVAILABLE" || args.status === "DISABLED") patch.status = args.status;
          const u = updateLoginCredential(c.id, patch, ctx.agentId);
          return ok(JSON.stringify({ success: true, credential_id: u.id, name: u.name, updated: Object.keys(patch) }));
        }
        default:
          return fail(`Unknown tool ${name}`);
      }
    } catch (err) {
      return fail(err instanceof Error ? err.message : String(err));
    }
  },
});
