#!/usr/bin/env node
/* ------------------------------------------------------------------
   Import skill documents from an upstream repository into Nexora's
   version-controlled library.

   The text is copied byte for byte and pinned to one commit: Nexora
   never edits an upstream document in place, because an agent reading
   it is told where it came from and must be able to check. Anything
   Nexora needs to say about a document lives beside it, labelled, in
   the `adaptation` field of the library entry — never inside the
   imported body.

   Usage: node scripts/import-skills.mjs [revision]
   ------------------------------------------------------------------ */
import fs from "node:fs";
import path from "node:path";

const REPO = "addyosmani/agent-skills";
const REV = process.argv[2] || "be4e44a9fbc5e8df0beaefadbb28bd22ee61cc39";
const RAW = `https://raw.githubusercontent.com/${REPO}/${REV}`;

const SKILLS = ["debugging-and-error-recovery", "frontend-ui-engineering", "code-review-and-quality", "test-driven-development"];
const REFERENCES = ["accessibility-checklist", "performance-checklist", "testing-patterns"];

const get = async (p) => {
  const r = await fetch(`${RAW}/${p}`);
  if (!r.ok) throw new Error(`${p} -> ${r.status}`);
  return r.text();
};

/** SKILL.md carries `name` and `description` in YAML frontmatter. */
function frontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) return { meta: {}, body: md };
  const meta = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^(\w[\w-]*):\s*(.*)$/);
    if (kv) meta[kv[1]] = kv[2].trim();
  }
  return { meta, body: md };
}

const lit = (s) => "`" + s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";

const skills = [];
for (const id of SKILLS) {
  const md = await get(`skills/${id}/SKILL.md`);
  const { meta } = frontmatter(md);
  skills.push({ id, name: meta.name ?? id, description: meta.description ?? "", body: md, path: `skills/${id}/SKILL.md` });
  console.log(`skill ${id}: ${md.length} bytes`);
}
const refs = [];
for (const id of REFERENCES) {
  const md = await get(`references/${id}.md`);
  refs.push({ id, body: md, path: `references/${id}.md` });
  console.log(`reference ${id}: ${md.length} bytes`);
}
const license = await get("LICENSE");

const out = `/* ------------------------------------------------------------------
   GENERATED by scripts/import-skills.mjs — do not edit by hand.

   Skill documents imported verbatim from ${REPO}
   at revision ${REV}.

   The bodies below are the upstream text, unchanged. Nexora's own
   notes about a document live in the library entry's \`adaptation\`
   field (src/lib/skills/library.ts), never inside the body — an agent
   reading a skill must be able to trust that what it reads is what the
   source says.
   ------------------------------------------------------------------ */

export const SKILL_SOURCE = {
  repo: ${JSON.stringify(REPO)},
  url: ${JSON.stringify(`https://github.com/${REPO}`)},
  revision: ${JSON.stringify(REV)},
  importedAt: ${JSON.stringify(new Date().toISOString().slice(0, 10))},
  license: "MIT",
  licenseText: ${lit(license)},
} as const;

export type ImportedDoc = { id: string; name: string; description: string; path: string; body: string };

export const IMPORTED_SKILLS: ImportedDoc[] = [
${skills.map((s) => `  {
    id: ${JSON.stringify(s.id)},
    name: ${JSON.stringify(s.name)},
    description: ${JSON.stringify(s.description)},
    path: ${JSON.stringify(s.path)},
    body: ${lit(s.body)},
  },`).join("\n")}
];

export const IMPORTED_REFERENCES: ImportedDoc[] = [
${refs.map((r) => `  {
    id: ${JSON.stringify(r.id)},
    name: ${JSON.stringify(r.id.replace(/-/g, " "))},
    description: "",
    path: ${JSON.stringify(r.path)},
    body: ${lit(r.body)},
  },`).join("\n")}
];
`;
fs.writeFileSync(path.join("src/lib/skills/imported.ts"), out);
console.log(`\nwrote src/lib/skills/imported.ts (${out.length} bytes) @ ${REV}`);
